FROM node:18
WORKDIR /app
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm run build:web

EXPOSE 3000
CMD [ "node", "server.js" ]